<a href="https://colab.research.google.com/github/coffyqah/data_science_w1/blob/main/tuto3ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#question 1
import numpy as np

arr = np.array([[2,3],[4,5]])
print(arr)


[[2 3]
 [4 5]]


In [ ]:
#question 2
import numpy as np

arr = np.random.randint(1, 10, size = (3, 4))
print(arr)


[[5 7 8 3]
 [4 4 2 9]
 [1 9 9 4]]


In [ ]:
#question 3
import numpy as np

#numpy array filled with ones
arr_one = np.ones((2,2))
print(arr_one)

#numpy array filled with zeros
arr_zero = np.zeros((3,4))
print("\n", arr_zero)


[[1. 1.]
 [1. 1.]]

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#question 4
import numpy as np

arr = np.random.randint(1, 10, size = (6,3))

print("before transpose:")
print(arr, end = "\n\n")

print("after transpose:")
print(arr.transpose())



before transpose:
[[5 5 3]
 [8 3 6]
 [4 8 3]
 [7 5 9]
 [7 6 6]
 [6 6 2]]

after transpose:
[[5 8 4 7 7 6]
 [5 3 8 5 6 6]
 [3 6 3 9 6 2]]


In [ ]:
#question 5
import numpy as np

arr1 = np.random.randint(1, 10, size = (2,3))
print("Array 1:")
print(arr1, end = "\n\n")
arr2 = np.random.randint(1, 10, size = (3,4))
print("Array 2:")
print(arr2, end = "\n\n")
print("Dot Product:")
print(np.dot(arr1, arr2))

Array 1:
[[7 9 9]
 [1 1 5]]

Array 2:
[[7 1 6 1]
 [6 7 5 6]
 [4 7 8 6]]

Dot Product:
[[139 133 159 115]
 [ 33  43  51  37]]
